services:
  - type: web
    name: badil-web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: mysql-badil
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: APP_NAME
        value: نظام إدارة البدلاء
      - key: APP_DIRECTORATE
        value: مديرية التربية والتعليم - يطا
    healthCheckPath: /
    autoDeploy: true
